# Generated by Django 2.0.6 on 2018-10-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penganjur', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Akvitivi',
            new_name='Aktiviti',
        ),
    ]
